# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down
version: '3'

services:
  backend:
    image: araceli09/back-end:1.0   # cambiar por tu usuario de dockerhub
    container_name: back-end
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - SERVER_URL=http://TUIPDELBACKEND:8085
      - DB_URL=jdbc:sqlserver://TUIPDELABASEDEDATOS:1433;databaseName=model;encrypt=true;trustServerCertificate=true
      - DB_USERNAME=sa
      - DB_PASSWORD=Araceli25
      - DB_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    networks:
      - my-network

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA
networks:
  my-network:
    name: my-network   # red compartida, visible desde ambos compose
    driver: bridge

# CONSUMIR UNA RED EXISTENTE CREADA POR OTRO COMPOSE
#networks:
#  my-network:
#    external: true   # usa la red creada por el compose de la base de datos