server:
  port: ${PORT:8085}
  url: ${SERVER_URL:http://localhost:8085}

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=RestuaranteDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: Araceli25
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none            # ← importantísimo: NO crear/alterar tablas
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.SQLServerDialect  # (opcional; Hibernate lo detecta)

  sql:
    init:
      mode: never               # ← ignora schema.sql/data.sql/import.sql si existen

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui         # abre: http://localhost:8085/swagger-ui
